[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_APP_URL = "/"
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_ENABLE_AUTH = "false"
  NEXT_PUBLIC_ENABLE_ANALYTICS = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
