[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://impact-verify.netlify.app"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_ENABLE_AUTH = "true"
  NEXT_PUBLIC_ENABLE_ANALYTICS = "false"
  NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN = "https://impact-verify.netlify.app"

# Use the Next.js plugin for proper asset handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static asset MIME types
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Content-Type = "image/*"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
