[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://impact-verify.netlify.app"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_ENABLE_AUTH = "true"
  NEXT_PUBLIC_ENABLE_ANALYTICS = "false"
  NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN = "https://impact-verify.netlify.app"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Add proper MIME types for common static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
