[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

# Ensure Next.js SSG files are correctly served with appropriate headers
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://impact-verify.netlify.app"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_ENABLE_AUTH = "true"
  NEXT_PUBLIC_ENABLE_ANALYTICS = "false"
  NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN = "https://impact-verify.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.netlify.app *.thirdweb.com fonts.googleapis.com fonts.gstatic.com; connect-src 'self' *.thirdweb.com api.thirdweb.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' data: *.thirdweb.com;"
